spring:
  application:
    name: ms-spring-loader
  datasource:
    url: jdbc:postgresql://localhost:5432/messages
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        order_inserts: true
    open-in-view: false
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: ms-spring-loader-group
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"

app:
  loader:
    topics: topic-1,topic-2,topic-3,topic-4
    listener-concurrency: 12
    writer-batch-size: 200
    writer-delay-ms: 250
    in-memory-buffer-capacity: 10000
