#!/bin/sh

set -eu

BROKERS="${BROKERS:-127.0.0.1:9092}"
TOPICS="${TOPICS:-topic-1,topic-2,topic-3,topic-4}"
COUNT="${COUNT:-20}"
DELAY_MS="${DELAY_MS:-100}"
KEY_PREFIX="${KEY_PREFIX:-tech-key}"
SOURCE_NAME="${SOURCE_NAME:-make-generator}"
QUERY_TYPE="${QUERY_TYPE:-LOAD}"
STATUS="${STATUS:-NEW}"

if ! command -v kcat >/dev/null 2>&1; then
  echo "kcat is not installed or not found in PATH" >&2
  exit 1
fi

IFS=','
set -- $TOPICS
IFS=' '

if [ "$#" -eq 0 ]; then
  echo "TOPICS must contain at least one topic" >&2
  exit 1
fi

topic_count=$#
i=1

while [ "$i" -le "$COUNT" ]; do
  index=$(( (i - 1) % topic_count + 1 ))
  eval "topic=\${$index}"

  produced_at=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  correlation_id="${KEY_PREFIX}-${topic}-${i}"
  key="${KEY_PREFIX}-${i}"

  payload=$(printf '{"eventId":"%s","sequence":%s,"topic":"%s","source":"%s","queryType":"%s","status":"%s","producedAt":"%s","payload":{"message":"generated by make + kcat","partitionHint":%s}}' \
    "$correlation_id" \
    "$i" \
    "$topic" \
    "$SOURCE_NAME" \
    "$QUERY_TYPE" \
    "$STATUS" \
    "$produced_at" \
    "$(( (i - 1) % 3 ))")

  printf '%s\n' "$payload" | kcat \
    -P \
    -b "$BROKERS" \
    -t "$topic" \
    -k "$key" \
    -H "correlationId=$correlation_id" \
    -H "source=$SOURCE_NAME" \
    -H "queryType=$QUERY_TYPE" \
    -H "status=$STATUS" \
    -H "producedAt=$produced_at"

  echo "sent message $i/$COUNT to $topic with key=$key"

  if [ "$i" -lt "$COUNT" ] && [ "$DELAY_MS" -gt 0 ] 2>/dev/null; then
    sleep_seconds=$(awk "BEGIN { printf \"%.3f\", $DELAY_MS / 1000 }")
    sleep "$sleep_seconds"
  fi

  i=$((i + 1))
done
